### ISSUE TITLE
Runtime error on windows

### ISSUE THREAD

**Issue by ChenTsur** [nmellado/Super4PCS#11] opened 2016-05-03 20:01 UTC
Hi Nicolas!

I've encountered a "vector subscript out of range" exception while running super4pcs on windows.It occured when i tried to run ComputeTransformation method.
I attached screen shots with specific break points indicating crash points (it happend when called addElement (Error entry 1) and inside it (Error entry 2):
if (_grid[pId] == NULL) _grid[pId] = new ChealMap(_ngLength); 

caused the carsh.

I am working on windwos 10 , VS15 opencv 3.1 and EIGEN from last December (downloaded as latest version).

My parameters (and .obj files):

std::string input1 = "hippo1.obj";
std::string input2 = "hippo2.obj";
std::string output = "output.obj";
double delta = 5.0;
double overlap = 0.2;
double thr = 1.0;
double max_color = 150;
int n_points = 200;
double norm_diff = 90.0;
int max_time_seconds = 10;
bool use_super4pcs = true;

Please advise me what is the problem.

Thanks!

ChenTsur

![error_entry_1](https://cloud.githubusercontent.com/assets/10323934/14996490/ec1662ec-1182-11e6-90aa-6940bce86d5b.png)
![error_entry_2](https://cloud.githubusercontent.com/assets/10323934/14996489/ec05354e-1182-11e6-8609-16e9ec186231.png)

**Comment by nmellado** [comment] 2016-05-03 20:20
Thanks for the report, I've managed to reproduce the error.

You use a very large value for delta, leading to very sparse re-sampled point clouds, which has the side effect to cause this crash.

I'll come back with a fix soon.
In the meantime, I recommend to use more realistic values, such as 0.01 for this example (from the runme-hippo.bat script).

Check advices on parameter setting in the wiki [usage](https://github.com/nmellado/Super4PCS/wiki/Usage) page.

**Comment by ChenTsur** [comment] 2016-05-03 20:33
I had made the change and now delta=0.01 all the other parameters are the same . Yet I had encountered another runtime error in the break point as shown at the added png.

Thanks!

ChenTsur


![error_entry_3](https://cloud.githubusercontent.com/assets/10323934/14997424/58de31da-1187-11e6-9763-b70fb8ed3306.png)

**Comment by diegonzalezb** [comment] 2016-05-04 01:48
Hello:

I have exactly the same issue: I'm trying to use the Super 4PCS on Windows 10 and I'm getting exactly the same error:

![super4pcs error](https://cloud.githubusercontent.com/assets/15080655/15003279/4e25ed32-1178-11e6-8d25-41bc2351ae9a.jpg)

I'm trying to use the code for aligning two small point clouds (represented in PLY files), which do not have face information.
Could maybe the size of the point clouds, (less than 500 points), or maybe not having any face information, bring some problems for the algorithm??

Any suggestions for fixing this issue will be greatly appreciated.

Thank you,

Diego.

**Comment by nmellado** [comment] 2016-05-17 15:50
First error fixed with commit bd96b63.
Second error in progress.

**Comment by ChenTsur** [comment] 2016-05-17 16:35
Thanks!

Keep us updated...

Chen
בתאריך 17 במאי 2016 18:50,‏ "Nicolas Mellado" <notifications@github.com>
כתב:

**Comment by diegonzalezb** [comment] 2016-05-17 17:35
Thanks a lot

**Comment by lhanes** [comment] 2016-05-18 09:38
Hi Nicolas,

I'm running Super4PCS on Windows 7 and I get a slightly different error to that mentioned above, though in the same place, so I thought it may have the same underlying cause.

At ExtractPairs->process->split->erase I get a "vector erase iterator outside range" exception.

![image](https://cloud.githubusercontent.com/assets/19425909/15353987/712c4580-1ce3-11e6-8287-ee22c68640fe.png)

I'm using it for 2 .obj triangular meshes, each around 75,000 vertices. I've also tried .obj meshes of around 500 vertices and get the exact same error.

The input parameters used are:
Overlap: 0.5
Delta: 1.0
Max time: 1000
Num Points: 400
Threshold: 1.0
Max Color: 1e9
All others left at default

Many thanks again for your library and spending the time to fix issues!

Laurence

**Comment by nmellado** [comment] 2016-05-18 09:44
Thanks for the several reports. 

However I cannot reproduce all the errors. 
Please open new issues to report a new bug, except if you have **exactly** the same error than reported in existing issues. 
I'll merge the issues when need.
It's easier for me to follow what are the different problems, and how to fix them.

**Comment by nmellado** [comment] 2016-05-18 16:18
@ChenTsur, @diegonzalezb , I cannot reproduce your error.

Could you please confirm me it is still occurring, for the hyppo models, and with the following parameters ?
> double delta = 5.0;
> double overlap = 0.2;
> double thr = 1.0;
> double max_color = 150;
> int n_points = 200;
> double norm_diff = 90.0;
> int max_time_seconds = 10;
> bool use_super4pcs = true;

Thanks !

**Comment by diegonzalezb** [comment] 2016-05-21 03:18
Hello Nicolas:

Thanks a lot for your reply...
(*) For the "hippo1.obj" and "hippo2.obj" that you provided as examples with your program, the code worked just fine with the parameters that you mentioned.

However, I have actually several doubts about how to use your code with other inputs: 
(I'm very sorry if this is perhaps not the place to comment and ask all of this):

1) I tried to load as input a pair of basic PLY files that are only Point clouds without any face information, (the files only have the info about the points and their normals). However, for loading this type of file, I had to modify the "io_ply.h" file, because in that ".h" file, the information about the faces is required.
I'm not really sure why is this the case??... It is just not possible to use your algorithm for inputs that have no face information?.

2) After doing this change in the "io_ply.h" file, I loaded the Ply files that I have, and it is then when the error that I had previously posted occurred... I understand that I was not supposed to do the change that I mentioned, but I really feel that your code should work with point clouds where there is no information about faces... or I'm just getting your algorithm very wrong??

Thanks a lot again.

Regards,

Diego

**Comment by nmellado** [comment] 2016-05-23 08:49
@diegonzalezb : You are right, Super4PCS works directly on point clouds, and doesn't need any face information to do the registration.

I've updated the wiki with the list of supported file formats: https://github.com/nmellado/Super4PCS/wiki/File-formats. 
Please check your files can be loaded, modify them, or open an issue if needed.

**Closed by nmellado** 2016-05-23 08:49 UTC
Labels: bug-win
