### ISSUE TITLE
Linking error on Mac

### ISSUE THREAD

**Issue by xinkang** [nmellado/Super4PCS#23] opened 2016-12-05 19:16 UTC
Hi Dr. Mellado,

This is a very interesting method and I want to give it a try.  I followed the compilation instruction to build from source on my macOS Sierra (10.12.1).  The cfitsio (3.390) was installed via Homebrew and the ANN was build from source with no problems.  However, I got the following linking error.  Could you please help me on this?  Thanks!

```
cmake -DCMAKE_BUILD_TYPE=Release -DANN_DIR=~/lib/ann_1.1.2/ ../Super4PCS/
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found CFITSIO: /usr/local/lib/libcfitsio.dylib  
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   chealpix

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/ben/Work/PoseEst/RPM/Super4PCS_build
Bens-MacBook-Pro:Super4PCS_build ben$ make
Scanning dependencies of target super4pcs_accel
[  9%] Building CXX object super4pcs/accelerators/CMakeFiles/super4pcs_accel.dir/normalHealSet.cpp.o
[ 18%] Linking CXX static library libsuper4pcs_accel.a
[ 18%] Built target super4pcs_accel
Scanning dependencies of target super4pcs_io
[ 27%] Building CXX object super4pcs/io/CMakeFiles/super4pcs_io.dir/io.cc.o
[ 36%] Linking CXX static library libsuper4pcs_io.a
[ 36%] Built target super4pcs_io
Scanning dependencies of target super4pcs_algo
[ 45%] Building CXX object CMakeFiles/super4pcs_algo.dir/super4pcs/4pcs.cc.o
[ 54%] Building CXX object CMakeFiles/super4pcs_algo.dir/super4pcs/super4pcs.cc.o
[ 63%] Linking CXX static library libsuper4pcs_algo.a
[ 63%] Built target super4pcs_algo
Scanning dependencies of target chealpix
[ 72%] Building C object 3rdparty/chealpix/CMakeFiles/chealpix.dir/src/chealpix.c.o
[ 81%] Linking C shared library libchealpix.dylib
[ 81%] Built target chealpix
Scanning dependencies of target Super4PCS
[ 90%] Building CXX object CMakeFiles/Super4PCS.dir/super4pcs/super4pcs_test.cc.o
[100%] Linking CXX executable Super4PCS
ld: can't open output file for writing: Super4PCS, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Super4PCS] Error 1
make[1]: *** [CMakeFiles/Super4PCS.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nmellado** [comment] 2016-12-05 21:38
Hi @xinkang ,

Thanks for the report.
I don't have a mac to test on my own, so let's try simple things first if you don't mind.

After a quick look online, it seems that this error can be caused by permission issues, e.g. clang doesn't have writing access in the build directory. Can you please check this ?

Another options would be that the output directory actually doesn't exist. Can you run the compilation with -v to see invocation ?

Cheers,
Nicolas

**Comment by xinkang** [comment] 2016-12-06 04:42
Hi @nmellado,

I found the reason.  In the `build` folder, there is a subfolder named `super4pcs` and the target executable's name is `Super4PCS`.  For some legacy reasons, by default the file name on Mac HFS+ Journaled format HD system is NOT case-sensitive.  In this case, the target executable's name has be occupied and cannot be created by `ld`.  There is no such issue on Linux (Ubuntu).  To support Mac, I guess the simplest solution might be changing the name of that (intermediate) subfolder to something else.  Hope this helps and you will update the repo soon.

Thanks,
Ben

**Comment by nmellado** [comment] 2016-12-06 11:57
Ok great thanks. Pushing changes ASAP.

Cheers,
Nicolas

**Comment by nmellado** [comment] 2016-12-06 13:57
@xinkang : could you please checkout branch [bugfix_23](https://github.com/nmellado/Super4PCS/tree/bugfix_23) and check it's solving the problem ?
You might need to clean and clear the cmake cache.

**Comment by xinkang** [comment] 2016-12-07 15:07
@nmellado, It works.  Thanks!
-Ben

**Comment by nmellado** [comment] 2016-12-07 15:30
Great, thanks for the report.
Branch merged with master.

**Closed by nmellado** 2016-12-07 15:30 UTC

**Comment by nmellado** [comment] 2016-12-08 09:28
Compilation instructions added in wiki
