### ISSUE TITLE
Windows version compile failed 

### ISSUE THREAD

**Issue by zengbw** [nmellado/Super4PCS#7] opened 2016-03-24 09:35 UTC
Hi,
   I have just download the latest version, which supports Windows platforms( https://github.com/nmellado/Super4PCS/wiki/Compilation ). My computer system is windows7, and I have installed the OpenCV3.1.0 and Eigen3.2.8. 
     But after I open Super4PCS.sln, and compile it. I got 20 errors. Just as following:
![image](https://cloud.githubusercontent.com/assets/12235439/14013009/ad6e9e6e-f1e4-11e5-90aa-9c3cf342a36d.png)

And the output window gave the message:
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1610,5): warning : The referenced project 'F:/Nicolas/Pro/code/git/Super4PCS/3rdparty/cfitsio/cfitsio.build/ZERO_CHECK.vcxproj' does not exist.
1>  ANN.cpp
2>  Building Custom Rule** F:/Nicolas/Pro/code/git/Super4PCS/3rdparty/cfitsio/CMakeLists.txt**
2> 系统找不到指定的路径( _System cannot find the path( file)_)。
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 3( _exit, code is 3_)。

      The front bold text is the issue, that it has the absolute path which seems is your (Nicolas) computer's path. The italic text is translation from Chinese.

     In my opinion, you can just provide the source code and give the step by step or the main steps of how to generate the Surper4PCS.sln by cmake. I believe it will be helpful for the windows user.
     Thanks a lot!

**Comment by nmellado** [comment] 2016-03-24 09:45
Thanks for the feedback, I will push a fix ASAP.

Right now it's a bit tricky to generate the sln solution directly from CMake, because of the dependencies. 
It's however temporary, I'm working at removing these dependencies to ease the installation process.

**Comment by nmellado** [comment] 2016-03-24 19:18
Should be fixed with 

- edb1c1f74d742d797981e7c3c9946f96e78f8d6d
- df9c0f4cf4397a4db1d6d931bafcf70f99e5dea5

Could you please confirm ?

**Comment by zengbw** [comment] 2016-03-25 02:09
Yes, it has fixed the absolute path problem. But  it still has some error in my IDE. Just as follow:
![20160325094004](https://cloud.githubusercontent.com/assets/12235439/14036152/063fecdc-f271-11e5-85ad-46e52022dde7.png)

Here I have two questions. Which version of Eigen do you use in the project? My Eigen is 3.2.8. As we can see from the output window that most of the errors are related to Eigen. So I think may be we can fix it by using the suitable version of Eigen. 
The other is that it has some errors in match_4pcs as the black rectangle frame show in the picture.
Could you please help to solve them?
 Thank you!

**Comment by nmellado** [comment] 2016-03-25 07:40
Compilation with Eigen 3.2.8 is fine for me.
Can you add more details about your configuration (VS2015 version, custom settings, compilation mode 32/64b, ...), so I can try to reproduce the problem ?

Just for testing, can you try to add /clr /c and see how it goes ?
https://msdn.microsoft.com/en-us/library/96kbe216.aspx

**Comment by zengbw** [comment] 2016-03-25 12:26
Now I have found the problem! It's the file code-format  and generate platform. If we open super4pcs.cc(called it as A) file by Notepad++, we can see that it's platform is UNIX and format is UTF-8 in the status bar. So I just make a new empty file(called it as B), and copy the context from A file. Then file B's platform is DOS\Windows and format is ANSI. After that I rebuild the Super4pcs project, and it's succeeded!
And can you tell me how to generate it by cmake(gui) in windows. I have try it by failed.
Thank you for your help!

**Comment by nmellado** [comment] 2016-03-25 12:59
Ok thanks, I will create an issues regarding potential encoding issues. 
However, UTF-8 is a good choice fro cross-platform code, and I will stick with it.

Regarding CMake: like I said, the process is not direct, mostly manual. This process will be improved once I'll removed the dependencies.

Thanks for your feedback.

**Closed by nmellado** 2016-03-25 12:59 UTC
Labels: compilation-problem
