### ISSUE TITLE
incorrect output of ply file

### ISSUE THREAD

**Issue by wpqjbzwm** [nmellado/Super4PCS#16] opened 2016-06-09 07:37 UTC
hi, @nmellado 
as you adviced, I open a new issue.
when ply format is used, the output ply file is not correct. Please check the attachments.

@ Super4pcs -i hippo1.ply hippo2.ply -o 0.7 -d 0.01 -t 1000 -n 400 -r super4pcs.ply
@ PAUSE

![clipboard01](https://cloud.githubusercontent.com/assets/19824533/15922045/2f7767c4-2e58-11e6-9379-cdcca0ca3dbc.jpg)

[hippos ply.zip](https://github.com/nmellado/Super4PCS/files/306347/hippos.ply.zip)

**Comment by nmellado** [comment] 2016-06-09 08:07
@wpqjbzwm : can you please confirm the proposed bugfix is solving your problems ?

**Comment by wpqjbzwm** [comment] 2016-06-09 08:30
@nmellado : Both cloudcompare and meshlab can not open output ply file, said errors in header. I'll give more try.

**Comment by wpqjbzwm** [comment] 2016-06-09 08:34
ply
format binary_little_endian 1.0
Super4PCS output file
element vertex 21935
property float x
property float y
property float z
end_header

I checked the header, maybe here should be: Comment Super4PCS output file.

**Comment by nmellado** [comment] 2016-06-09 08:36
Probably closed now.
Sorry, was due to a typo introduced in previous commit.

**Comment by wpqjbzwm** [comment] 2016-06-09 08:40
output file can be opened now, but is still incorrect. Not a big problem because the transformation is correct. I'll try it under Linux. Thanks @nmellado

**Comment by wpqjbzwm** [comment] 2016-06-09 12:50
Failed to compile it under Linux, I'm a freshman in Linux. Sorry, @nmellado.

**Comment by nmellado** [comment] 2016-06-10 09:13
Bug confirmed for Windows build (working with Linux).

**Comment by nmellado** [comment] 2016-08-25 13:19
Bug seems to be fixed with 7cc35e0.
ply and obj files now produce the same output files on windows, which can be opened with meshlab (tested with v1.3.3).


Closing.

**Closed by nmellado** 2016-08-25 13:19 UTC
Labels: bug-win
